### PR TITLE
Fix ComboBox typings for trigger props

### LINKED ISSUE #257: Fix ComboBox typings for trigger props

### PR DESCRIPTION
**Pull request by LamaEats**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #257 

## QA Instructions, Screenshots, Recordings
  
in all place where ComboBox using with `renderTrigger` prop may pass generic type for trigger element ref
Otherwise type will be calculated as `HTMLElement`

```tsx
// in this case ref prop will have `HTMLSpanElement` as type on ref element
<ComboBox<HTMLSpanElement>
    renderTrigger={({ ref }) => <span ref={ref}>trigger</span>}
    ...
/>

...

// in this case ref prop will have `HTMLElement` as type on ref element by default
<ComboBox
    renderTrigger={({ ref }) => <span ref={ref}>trigger</span>}
    ...
/>
```

### CODE REVIEW

File: src/components/ComboBox.tsx [hunk 1]
```diff
@@ -73,145 +73,150 @@ const StyledErrorTrigger = styled.div`
...
+                </div>
+            </Popup>
+        </StyledComboBox>
+    );
+}
+
+export const ComboBox = <T extends HTMLElement>(
+    props: React.PropsWithoutRef<ComboBoxProps<T>> & React.RefAttributes<HTMLDivElement>,
+) => {
+    return React.forwardRef<HTMLDivElement, typeof props>(ComboBoxRenderFunction)(props);
```
Comment (9teen90nine) [inline src/components/ComboBox.tsx:219]: Shouldn't it also be HTMLElement?

**Review by 9teen90nine — APPROVED** [review]

File: src/components/ComboBox.tsx (hunk 1 above)
Comment (LamaEats) [reply src/components/ComboBox.tsx:219]: no
