### PR TITLE
Fix align icons in GlobalSearch component

### LINKED ISSUE #528: Fix align icons in GlobalSearch component
Reference issue https://github.com/taskany-inc/issues/issues/1807

### PR DESCRIPTION
**Pull request by LamaEats**
## PR includes

- [x] Bug Fix
- [x] Refactor

## Related issues

Resolve #528

### CODE REVIEW

File: src/components/Input/Input.tsx [hunk 1]
```diff
@@ -13,49 +13,18 @@ interface InputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, '
...
-
-// eslint-disable-next-line @typescript-eslint/no-unused-vars
-const StyledInput = styled(({ forwardRef, size, view, brick, iconLeft, iconRight, ...props }: InputProps) => (
-    <input ref={forwardRef} {...props} />
-))`
     box-sizing: border-box;
-    width: 100%;
 
-    font-weight: 500;
+    gap: 9px;
```
Comment (awinogradov) [inline src/components/Input/Input.tsx:22]: Hmm... what the number?)

Comment (LamaEats) [reply src/components/Input/Input.tsx:22]: Same question about this prop: `padding-left: 30px; // 8 + 8 + 15 - 1` 😄 

But based on this calculation a gap's value must be `8px`

**Review by awinogradov — APPROVED** [review]

**Review by nyet-ty — APPROVED** [review]
